Configure Promtail to send logs to Grafana Loki
seattleflu/infra pull request #7
Opened 2021-03-25 01:28 UTC by kschwabefry

Use promtail to send logs from paths matching /var/log/*log to
our managed Grafana Loki instance, for aggregation and viewing
alongside other metrics

2021-03-25 01:29 UTC, kschwabefry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set up Grafana Loki and promtail for unified log store](https://trello.com/c/uc3nU0F7/938-set-up-grafana-loki-and-promtail-for-unified-log-store)

2021-03-25 19:42 UTC, tsibley requested changes
Great work so far! I left a bunch of specific comments on various chunks below.

2021-03-25 19:42 UTC, tsibley commented on files/etc/systemd/system/promtail.service
> +WantedBy=multi-user.target
I think we'll want to tweak this service definition a bit more, e.g.:

- Don't run as root, but as a dedicated promtail user. This may require adjusting permissions/ACLs to allow promtail to read some files which are not world-readable.
- Add a [`Restart` strategy](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) so the service stays up after error
- Add an `ExecReload` command if promtail supports signaling of graceful reload

2021-03-25 19:42 UTC, tsibley commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
Does this API key work for pushing to Loki too? We may need to adjust its permissions on the Grafana Cloud management side or mint a separate API key for Loki.

2021-03-25 19:42 UTC, tsibley commented on tasks/promtail.yaml
> +    src: promtail-linux-amd64
These three steps can be reduced a bit to avoid some steps and also make the downloading conditional on the executable already existing. See the `uwsgi_exporter` install steps for an example:

https://github.com/seattleflu/infra/blob/7e64e58d6ec6c799dda198bfe2336eee6a0c32b8/tasks/prometheus.yaml#L9-L23

2021-03-25 19:42 UTC, tsibley commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
As this is a secret value, we'll want to set permissions on the file accordingly.

It is also a little strange to me that this file is used by promtail (and managed in this tasks file) but installed into `/etc/prometheus`.

2021-03-25 19:42 UTC, tsibley commented on tasks/promtail.yaml
> +      - unzip
We can avoid this step by downloading the tar.gz release archive instead of the zip.

2021-03-25 19:42 UTC, tsibley commented on files/etc/promtail/promtail.yml
> +  static_configs:
Reading from files with `static_configs` is a great place to start, but I think we'll sooner-than-later want to pull from a couple other places as well:

1. `journal` for the systemd-journald, which will contain additional automatic labels like the service/unit that produced the log lines. I expect these will be very nice for filtering and contextualizing. Tricky bit is that journald currently forwards to syslog as well, so we'll want to either a) stop that by tweaking journald's config or b) make sure that our syslog slurping filters out logs originating from journald. I think both are possible, but (a) has maybe bigger ramifications for how we find logs on-host?
2. `syslog` to have rsyslog write logs directly to promtail, which will contain additional automatic labels like the logging ident, level/severity, and facility that I expect to be nice for filtering and contextualizing. This will require the addition of a line or two to the rsyslog config.
3. `static_configs` for /var/log/… remains for log files written directly by various programs and services (like apt, unattended-upgrades, Apache, uwsgi, etc).

I don't think we need to do all that to get started, but it might be easier (albeit slower) to think about it now?

2021-03-26 01:26 UTC, kschwabefry commented on files/etc/promtail/promtail.yml
> +  - url: https://logs-prod-us-central1.grafana.net/api/prom/push
So, I pulled this from various documentation on the setup:
https://grafana.com/docs/grafana-cloud/quickstart/logs_promtail_linuxnode/
https://grafana.com/docs/grafana-cloud/logs/collect_logs/
https://grafana.com/orgs/seattleflu/hosted-logs/18857#sending-logs

And I can confirm the logs did show up in Loki when I was testing it out.

When you say prom remote writer endpoint, are you asking if its getting ingetsed into Loki by way of Prometheus  instead of directly to Loki?

2021-03-26 01:26 UTC, kschwabefry commented on files/etc/promtail/promtail.yml
> +  filename: /tmp/positions.yaml
Thanks for calling it out, not clearing between boots definitely makes more sense. I'll move it out of /tmp and under /var. I wish the documentation was a little more consistent here - I pulled this path from documentation as well (a few places including https://grafana.com/docs/grafana-cloud/logs/collect_logs/).

2021-03-26 01:27 UTC, kschwabefry commented on files/etc/promtail/promtail.yml
> +  grpc_listen_port: 0
Similarly I had picked this up from example config in documentation, and it does mean it assings a port randomly. Happy to change, if you think there's advantages to a fixed port. If we don't specify these, the defaults are:

```
http_listen_port: 80
grpc_listen_port: 9095
```

(source: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#server)

Does that seem reasonable here?

2021-03-26 01:28 UTC, kschwabefry commented on hosts/development
> +ansible_python_interpreter=/usr/bin/python3
This may well have been from when I tested installation as a docker image instead of from the binary. I'll test out removal as I'm tinkering with the other updates!

2021-03-26 01:31 UTC, kschwabefry commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
Yep, it did indeed (for the endpoint I'm using anyhow.) Would you prefer separate keys?

2021-03-26 01:32 UTC, kschwabefry commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
Thats fair - if we are going to share the key, how about I move to /etc/grafana?

2021-03-26 01:35 UTC, kschwabefry commented on files/etc/systemd/system/promtail.service
> +WantedBy=multi-user.target
I had originally tried adding a handler for promtail reloaded, but iirc it wasn't supported directly. I didn't know about execreload - I'll try adding to the service definition here. Thanks!

2021-03-29 17:54 UTC, tsibley commented on files/etc/promtail/promtail.yml
> +  filename: /tmp/positions.yaml
Yeah, agreed about consistency within the Grafana docs. FWIW, I've found the reference material to be most reliable. The guides and tutorials seem to me to be a bit scattered and most focused on time-to-completion (e.g. "copy and paste this") rather than understanding best practices for production.

2021-03-29 19:04 UTC, kschwabefry commented on files/etc/promtail/promtail.yml
> +  static_configs:
These are good suggestions, thanks. I'm not sure if we need all of these initially, but I can spend some more time, particularly with the journal and syslog options and try to figure out if it makes sense to make this more comprehensive out the gate.

2021-03-29 19:49 UTC, tsibley commented on files/etc/promtail/promtail.yml
> +  grpc_listen_port: 0
I'd probably drop `grpc_listen_port` since that's the default value. For HTTP, port 80 isn't available as it's already bound by Apache on our host. Most Prometheus exporters things use [ports in the 9100–9999 range](https://github.com/prometheus/prometheus/wiki/Default-port-allocations), though there doesn't seem to be one registered for promtail. All that really matters is that we choose something that's free on our host.

2021-03-29 19:50 UTC, tsibley commented on files/etc/systemd/system/promtail.service
> +WantedBy=multi-user.target
Nod. I don't know if promtail respects SIGHUP or similar for reloading; it may not.

2021-03-29 20:00 UTC, tsibley commented on files/etc/systemd/system/promtail.service
> +WantedBy=multi-user.target
Seems like not given [this open 2y old issue](https://github.com/grafana/loki/issues/16) and [this signal handling registration in promtail](https://github.com/grafana/loki/blob/6ab0e9457267c767a3451b74890cf41d98a3e72e/pkg/promtail/server/server.go#L259-L264).

2021-03-29 20:00 UTC, tsibley commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
Nope, I think that's fine!

2021-03-29 20:05 UTC, tsibley commented on files/etc/promtail/promtail.yml
> +  - url: https://logs-prod-us-central1.grafana.net/api/prom/push
Ahh, I see it's indeed the same endpoint that Prometheus (via its [remote write feature](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage)) uses to push metrics to Grafana Cloud. As I understand it, Loki logs are not "just" special Prometheus metrics, so using the same endpoint is weird and unexpected to me, but my understanding may be incomplete and/or I bet there's a good reason for it!

2021-03-29 20:06 UTC, tsibley commented on tasks/promtail.yaml
> +    dest: /etc/prometheus/grafana-cloud-api-key
Good idea!

2021-03-29 20:09 UTC, tsibley commented on files/etc/promtail/promtail.yml
> +  static_configs:
Sounds good, thanks. If it's a bigger ball of wax to deal with at the moment, we can punt for now. Having logs in Loki at all will allow us to do a lot of useful things even without more specific labeling. The only case I can see it being necessary right away is if we find we need more specific labeling to narrow down the logs enough so that text-based filters aren't slow.

2021-06-09 19:07 UTC, tsibley commented on tasks/promtail.yaml
> +      - unzip
Actually, there are only zip archives, so we can't!

2021-06-14 23:47 UTC, tsibley commented
Pushed a slew of small commits addressing suggestions from my previous review. I've tested this locally in dev (incl. pushing to Loki for real; see related commit 90566c3 for more details) and it seems to work well.

I'd appreciate additional 👀 on it if folks have the inclination and time. Would definitely like to see this long-standing WIP get merged so we can start reaping the benefits!

There is still room for future improvement, including:

- Adding [pipeline](https://grafana.com/docs/loki/latest/clients/promtail/pipelines/) stages to better surface some kinds of log data
- Investigating if we're handling multi-line log messages correctly. There's a new feature in promtail 2.2 for this and Grafana's UI when browsing logs indicates that we may be doing it wrong. We're not configuring this explicitly, so the defaults may not be sufficient.

2021-07-13 23:02 UTC, tsibley commented
I re-pushed to address two things that came up in offline discussion with @kschwabefry:

1. Stop sharing the Grafana Cloud API key between Prometheus and promtail. Each service gets its own copy, which simplifies permissions and avoids dependencies between our Ansible task files.
2. Rewrote commit message describing the [handler re-ordering](https://github.com/seattleflu/infra/pull/7/commits/70e148fc9e0b4b298014a10b884d00d1557c264a) to hopefully be clearer for posterity.

Here's a [range-diff of the repush](https://tsibley.net/paste/2021-07-13wNSmtOFv-diff-rebase.html), since GitHub's own range diff doesn't highlight changes to commit messages or per-commit matchings.

2021-07-13 23:04 UTC, tsibley commented
The plan is for @kschwabefry or I to merge and deploy this PR this week, which can be done, for example, by running:

```
ansible-playbook backoffice.yaml -i hosts/production --vault-id seattleflu@prompt
```

2021-07-14 21:52 UTC, kschwabefry reviewed
Thanks @tsibley for chatting about this and your work on these changes!

2021-07-14 21:58 UTC, merged